before_install:
  - gem install bundler

rvm:
  - 1.9.3

gemfile:
  - Gemfile
  - ci/Gemfile.rails3
  - ci/Gemfile.rails31
  - ci/Gemfile.rails32

matrix:
  include:
    - rvm: 2.0.0
      gemfile: ci/Gemfile.rails32
    - rvm: 1.9.2
      gemfile: ci/Gemfile.rails32
    - rvm: jruby-19mode
      gemfile: ci/Gemfile.rails32
    - rvm: rbx-19mode
      gemfile: ci/Gemfile.rails32